
default: &default
  adapter: postgresql
  encoding: unicode
  username: danielc      
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_stocksapp_development

test:
  <<: *default
  database: rails_stocksapp_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
